# Generated by Django 3.1.5 on 2021-01-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20210129_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('floor', models.IntegerField(default=1)),
                ('room', models.TextField(max_length=50)),
            ],
        ),
    ]
