# Generated by Django 3.1.5 on 2021-01-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.room'),
        ),
    ]
